Fixed installing zc.recipe.egg: force non binary install.
You do get an error after install, which is solved when you restart buildout:

  Running setup.py install for zc.recipe.egg ... done
Successfully installed zc.recipe.egg-2.0.3
While:
  Installing.
  Getting section test.
  Initializing section test.
  Loading zc.buildout recipe entry zc.recipe.egg:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 2013, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 568, in install
    [self[part]['recipe'] for part in install_parts]
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1153, in __getitem__
    options._initialize()
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1257, in _initialize
    self.initialize()
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1263, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1222, in _install_and_load
    req.project_name, group, entry)
  File "/Users/maurits/tmp/buildout3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/maurits/tmp/buildout3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/maurits/tmp/buildout3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/maurits/tmp/buildout3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named recipe.egg